- hosts: localhost
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  tasks:
  - name: Deploy the service
    community.kubernetes.k8s:
      state: present
      definition: "{{ lookup('template', 'service.yml') | from_yaml }}"
      validate_certs: no
      namespace: default
  - name: Deploy the application
    community.kubernetes.k8s:
      state: present
      validate_certs: no
      namespace: default
      definition: "{{ lookup('template', 'deployment.yml') | from_yaml }}"
