apiVersion: v1
kind: Service
metadata:
  name: kubernetes-configmap-reload

spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: kubernetes-configmap-reload

